### ISSUE TITLE
dct:issued on dcat:Dataset: if the relaease date is in the future the datasets should not be published

### ISSUE THREAD

**Issue by sabinem** [opendata-swiss/dcat_ap_ch#167]
**Property**: dct:issued
**Class**: dcat:Dataset
**Implementation**: visiblity of datasets with dct:issued in the future
**Conformance to DCAT-AP CH**: not conformant to DCAT-AP CH since the usage note on dct:issued says, that datasets with a future relase date should not be published
**Details**: Currently it is possible to set a datasets visibilty to published regardless of whether the release date of that dateset is in the future or not.
**Proposal**: Correct implementation on opendata swiss: a dataset's visibility should not be published if the release date is in the future.

**Comment by Juan-Juan-1** [comment]
What's the difference between this issue and https://github.com/opendata-swiss/dcat_ap_ch/issues/171 ?

**Comment by sabinem** [comment]
This is a duplicate to #171.
