### ISSUE TITLE
Extension dct:availability

### ISSUE THREAD

**Issue by l00mi** [opendata-swiss/dcat_ap_ch#188]
**Property**: `dct:availability` 
**Class**: `dcat:Dataset`
**Implementation**: To be discussed, but to make it clear that it is not a guaranteed sevice, implemented as a CV with a list of brought Availability measures tbd, (e.g. shortTerm (1 year), midTerm (5 years), longTerm (10 years)).

**Conformance**: For real world applications it is important to quickly understand how long a dataset will stay available to quickly decide if it can be used in a (data-) project. The goal is to provide a data provider statement regard the long-term availability of the provided dataset. This should be made conform to the efforts on the DCAT-AP level, see below.

**Comment by sabinem** [comment]
@l00mi DCAT-AP has a similar property on dcat:Distribution: `dcatap:availability` 
See: https://github.com/SEMICeu/DCAT-AP/issues/18
![Screenshot from 2021-11-23 07-46-41](https://user-images.githubusercontent.com/5292683/142981397-c99e4458-7f3a-4588-8bf1-e0cd59e122bf.png)

As far as I understand they are planning to have a controlled vocabulary for this property, see this discussion here: https://github.com/SEMICeu/DCAT-AP/issues/190#issuecomment-825494317

If possible we should not to reinvent the wheel ourselves, but put first participate in the discussion there and see what of our needs can be already covered by DCAT-AP.

**Comment by l00mi** [comment]
@sabinem that is good to hear. I was no aware of this effort. I think that sounds very aligned to the proposition and I would push to adapt it. I could not find a CV defined already?

Finally I would strongly suggest to allow it also on the Dataset level and not only on the Distribution level. It does provide different meaning to say if a Distribution stays available (and is updated with new data) vs. the whole Dataset will stay maintained.

**Comment by l00mi** [comment]
Yes this works for me, and the proposed list is enough from my point of view. The only caveat so far, it is on the Distribution right now. I would like to see it (also) on the Dataset.

**Comment by andreasamsler** [comment]
In addition, it could be valuable to know whether a dataset is being used and by which administrative agencies/bodies (as well as by which third parties under certain circumstances).

**Comment by l00mi** [comment]
closing this in favor of https://github.com/opendata-swiss/dcat_ap_ch/issues/187
