### ISSUE TITLE
Add a field for metadata modification date

### ISSUE THREAD

**Issue by fabian-santi** [opendata-swiss/dcat_ap_ch#218]
While the usage of dct:modified has been discussed and perfected (https://github.com/opendata-swiss/dcat_ap_ch/issues/179), and will be made easier to use and understand by the inclusion of DatasetSeries, I would suggest that we could include a separated optional field for the metadata modification date

- Modifications to the data: dct:modified
- Modifications to the metadata: dct:modified_metadata (or other name). This will allow to see when there are modification to the description, publisher, ... of the data, without affecting the data itself

**Comment by metaodi** [comment]
I'm not sure this is needed (see my comment in https://github.com/opendata-swiss/dcat_ap_ch/issues/179#issuecomment-2173370922).

How could a consumer of this information benefit from this change?

**Comment by fabian-santi** [comment]
@metaodi 
I added the suggestion after rather long discussions on this topic. Some in our group thought that if you correct a spelling mistake in the dataset description, the dct:modified should not be updated, since the change is basically not relevant and should not trigger updates or new analyses, but it is hard to say which are relevant changes and which are not. With this, it would become clear if you need to update your analysis (because the data is updated) or not (because only metadata was modified), while still keeping track of the metadata updates as well.

**Comment by mispichtig** [comment]
I would like to invite you to take a look at the usage notes of DCAT-AP CH v2 and adapt, add or highlight ambiguities accordingly. The aim should be to define a usage note that is understandable to data publishers on how to use the dct:modified property on the corresponding class. As an aid, those from DCAT-AP 3 and inputs from Issue 179 are available in the table. 

**dct:modified** overview definition and usage notes:

| Class         | **Definition   (DCAT-AP CH)**                                                              | **Usage Note (DCAT-AP CH)**                                                                                          | Definition (DCAT-AP 3.0.0)                                                      | Usage (DCAT-AP 3.0.0)                                                          | Proposal eCH Issue 179                                                                                               |
|------------------|-----------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------|--------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------|
| **Catalog**      |                                            |   This property contains the most recent date on which the Catalogue was modified.                 | The most recent date on which the Dataset was changed or modified.                                                                             | -                                                                                                                   |
| **Dataset**      | This property contains the most recent date on which the Dataset was changed or modified. | - No value may indicate that the Dataset has never changed after its initial publication, or that the date of the last modification is not known, or that the Dataset is continuously updated. - This property MUST only be set if the distributions (the actual data) that the Dataset describes have been updated after it has been issued. In this case the property MUST contain the date of the last update. That way a person or institution using the data for an analysis or application will know when to update the report or application on their side. | The most recent date on which the Dataset was changed or modified.               | -                                                                              |  the date of the last change (if any) of the dataset OR the distributions (no matter if it's the metadata or the actual data). I understand, that this is a bit more complicated on the distribution level, but I would keep it simple: if there was a change, update the data (no matter if it's the data itself or the metadata). As long as the structure of the data is still the same, it's safe for a consumer to update the data.  |
| **Distribution** | This property contains the most recent date on which the Distribution was changed or modified. | The most recent date on which the Distribution was changed or modified.                               | The most recent date on which the Distribution was changed or modified.          | -                                                                              | However if the structure was changed, it's important to create a new distribution with a new ID to indicate this change. Maybe an implementation note could be added to make this distinction clear. See comment: https://github.com/opendata-swiss/dcat_ap_ch/issues/179#issuecomment-2173370922                                                                 |
| **Dataset Series** | This property contains the most recent date on which the Dataset Series was changed or modified. | This is not equal to the most recent modified dataset in the collection of the dataset series.        | The most recent date on which the Dataset Series was changed or modified.        | This is not equal to the most recent modified dataset in the collection of the dataset series. | -                                                                                                                   |

**Comment by taniahumar** [comment]
side note for **geodata**: date for metadata modification is mandatory (datastamp)

**Comment by mchaamsler** [comment]
I would like to strongly support the solution that Odi has formulated for the mentioned user need in issue #179 : https://github.com/opendata-swiss/dcat_ap_ch/issues/179#issuecomment-2173370922

A usage note is needed in this respect - which helps the user to understand what they can expect.

**Comment by mispichtig** [comment]
Decision eCH Working Group (13.08): no creation of a new property metadata field modified
define clear usage note about dct:modified, see: https://github.com/opendata-swiss/dcat_ap_ch/issues/179#issuecomment-2309527759
